# Generated by Django 3.2.9 on 2021-12-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shortdesc',
            field=models.TextField(default='notop'),
            preserve_default=False,
        ),
    ]
