# Generated by Django 3.2.9 on 2021-12-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=200)),
                ('parent', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('timeStamp', models.DateField()),
            ],
        ),
    ]
