# Generated by Django 3.2.9 on 2021-12-05 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211205_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
