# Generated by Django 3.2.9 on 2021-12-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='slug',
        ),
    ]
