# Generated by Django 3.2.9 on 2021-12-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_postimage_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='catogery',
            field=models.CharField(choices=[('people', 'People'), ('nature', 'Nature'), ('food', 'Food'), ('work', 'Work')], default='nature', max_length=200),
        ),
    ]
