# Generated by Django 3.2.9 on 2021-12-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='mymail@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
